import type { Metadata } from 'next';
import { Document } from '@/components/Document';
import { Theme, ThemeContextProvider } from '@/components/ThemeContext';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const f = () => {
    const cookieStore = cookies();
    const themeCookie = cookieStore.get('theme');

    return themeCookie?.value ?? 'light';
  };

  return (
    <ThemeContextProvider ssrValue={f() as Theme}>
      <Document>{children}</Document>
    </ThemeContextProvider>
  );
}
